SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d') SALES_DATE,
       PRODUCT_ID,
       USER_ID,
       SALES_AMOUNT
FROM ONLINE_SALE
WHERE DATE_FORMAT(SALES_DATE, '%m') = '03'
UNION ALL
SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d') SALES_DATE,
       PRODUCT_ID,
       NULL USER_ID,
       SALES_AMOUNT
FROM OFFLINE_SALE
WHERE DATE_FORMAT(SALES_DATE, '%m') = '03'
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID