-- 코드를 입력하세요
SELECT a.PRODUCT_CODE, sum(a.PRICE * b.SALES_AMOUNT) SALES -- 출력한 곳 만들기
FROM PRODUCT a, OFFLINE_SALE b
WHERE a.PRODUCT_ID = b.PRODUCT_ID -- 같다는 쿼리
GROUP BY a.PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC -- 조건문