SELECT s.SALES_DATE ,  s.PRODUCT_ID, s.USER_ID, s.SALES_AMOUNT
FROM ONLINE_SALE s RIGHT OUTER JOIN OFFLINE_SALE d on s.PRODUCT_ID = d.PRODUCT_ID
ORDER BY s.SALES_DATE asc , s.PRODUCT_ID asc, s.USER_ID  asc;