SELECT A.ID
FROM ECOLI_DATA AS A
         JOIN ECOLI_DATA AS B ON A.PARENT_ID = B.ID
         JOIN ECOLI_DATA AS C ON B.PARENT_ID = C.ID
WHERE C.PARENT_ID IS NULL
ORDER BY A.ID ASC;

-- 제가 푼거 아니고 질문하기에서 퍼왔스빈다.