-- 코드를 입력하세요
SELECT s.REST_ID, s.REST_NAME, s.FOOD_TYPE,s.FAVORITES,s.ADDRESS, ROUND(AVG(d.REVIEW_SCORE),2) "SCORE"
FROM REST_INFO s JOIN REST_REVIEW d  ON s.REST_ID  =  d.REST_ID

GROUP BY s.REST_ID, s.REST_NAME, s.FOOD_TYPE,s.FAVORITES,s.ADDRESS
ORDER BY SCORE desc, s.FAVORITES desc
;